import { afterEach, beforeEach, describe, expect, it } from "vitest";
import type { PGlite } from "@electric-sql/pglite";
import { listInvites } from "@/lib/invites/list";
import {
  createTestDb,
  pgliteListInvitesAdapter,
  seedInvite,
  seedMember,
} from "./db";

describe("listInvites (S1 integration seam)", () => {
  let db: PGlite;

  beforeEach(async () => {
    db = await createTestDb();
  });

  afterEach(async () => {
    await db.close();
  });

  it("orders PENDING before claimed, each group newest-first, and resolves display names", async () => {
    const admin = await seedMember(db, {
      firstName: "Admin",
      lastName: "User",
      role: "admin",
    });
    const claire = await seedMember(db, {
      firstName: "Claire",
      lastName: "Claimer",
    });
    const dan = await seedMember(db, { firstName: "Dan", lastName: "Doe" });

    // Claimed invites are deliberately the *newest* of all, to prove the
    // PENDING-first group rule beats raw recency.
    await seedInvite(db, {
      code: "INV-CLM-NEW",
      createdAt: "2026-03-02T00:00:00Z",
      claimedBy: dan,
      generatedBy: admin,
    });
    await seedInvite(db, {
      code: "INV-CLM-OLD",
      createdAt: "2026-03-01T00:00:00Z",
      claimedBy: claire,
      generatedBy: admin,
    });
    await seedInvite(db, {
      code: "INV-PND-NEW",
      createdAt: "2026-02-02T00:00:00Z",
      generatedBy: admin,
    });
    // A legacy invite with no recorded author -> blank "Generated by".
    await seedInvite(db, {
      code: "INV-PND-OLD",
      createdAt: "2026-01-01T00:00:00Z",
      generatedBy: null,
    });

    const invites = await listInvites(pgliteListInvitesAdapter(db));

    expect(invites).toEqual([
      { code: "INV-PND-NEW", claimedBy: "PENDING", generatedBy: "Admin User" },
      { code: "INV-PND-OLD", claimedBy: "PENDING", generatedBy: "" },
      { code: "INV-CLM-NEW", claimedBy: "Dan Doe", generatedBy: "Admin User" },
      {
        code: "INV-CLM-OLD",
        claimedBy: "Claire Claimer",
        generatedBy: "Admin User",
      },
    ]);
  });
});
